id: IB47A5B45
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
source_file: null
initial_creation_type: input
imported: '2022-05-27T19:06:18.805590'
last_modified: '2022-05-27T19:06:18.805603'
parser: null
source_metadata:
  title: 'MSV 6,09: Māṇavikā'
  language: zh
  base:
    fCA9F:
      title: Māṇavikā
      base_file: fCA9F.txt
      order: 1
  chapter_to_tile: {}
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
